import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import SmallCard from '@/components/SmallCard'
import MediumCard from '@/components/MediumCard'
import LargeCard from '@/components/LargeCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home({exploreData, cardsData}) {
  return (
    <>
      <Head>
        <title>Airbnb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      {/* Header */}
      <Header />
      {/* Banner */}
      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-semibold pb-5'>Explore Nearby</h2>

          {/* Pull some data from aserver - API endpoints */}
          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {
              exploreData?.map(({img, distance, location},idx) => (
                <SmallCard 
                  key={idx}
                  img={img} 
                  distance={distance} 
                  location={location} 
                />
              ))
            }
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-5'>Live Anywhere</h2>
          
          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {cardsData?.map(({img, title}, idx) => (
              <MediumCard 
                key={idx}
                img={img}
                title={title} 
              />
            ))}
          </div>
        </section>

        <LargeCard 
          img='https://links.papareact.com/4cj'
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const exploreData = await fetch('http://localhost:5000/airbnb/explore')
                              .then(res => res.json())
  const cardsData = await fetch('http://localhost:5000/airbnb/cards')
                              .then(res => res.json())

  return {
    props: {
      exploreData,
      cardsData
    }
  }
}